
all:
	cd bison_json && $(MAKE) -w
	# cd cpeg_calc && $(MAKE) -w
	cd cpeg_json && $(MAKE) -w
	cd cpeg_java && $(MAKE) -w
	# cd cpp-peglib && $(MAKE) -w
	cd misc && $(MAKE) -w
	cd cpeg_mouse_to_cpeg && $(MAKE) -w
